### PR TITLE
create BubbleSort dart

### PR DESCRIPTION
**Pull request by Sscuber03**

### CODE REVIEW

**Review by mursalfk — CHANGES_REQUESTED** [review]
Please add some more details about the code inside file by commenting.

**Comment by Sscuber03** [comment]
ok, will do that. Thank you for the review!

**Comment by Sscuber03** [comment]
Should i close this pr, and open a new one? or just let this be? I am new to open source, and am a bit confused about making changes to a pr. A bit of help will be appreciated immensly. Thank you!

**Comment by mursalfk** [comment]
No No... You have to make the changes in the same PR

**Review by mursalfk — APPROVED** [review]
Nice! Thank you for your submission.
I am merging this Pull Request

**Comment by mursalfk** [comment]
🎊 Congratulations. Your PR is merged 🎉

**Pull request merged**
